Repository part2-8team/Rolling, pull requests merged in 2024-05, with the labels that each got.

#16 Recipients api 로직 구현
  .babelrc
  jest.config.cjs
  jest.setup.js
  package.json
  src/App.test.jsx
  src/api/etcApi.js
  src/api/recipientApi.js
  src/test.txt
  yarn.lock
Labels: 완료, 기능

#21 Carditems 주강산
  .eslintrc.js
  .prettierrc.json
  src/pages/Card.jsx
  src/pages/CardItems.jsx
  src/pages/PostPage.jsx
  src/styles/GlobalStyles.jsx
  test.js
  yarn.lock
Labels: 진행중

#24 Message api 로직 구현
  src/api/messageApi.js
  src/api/recipientApi.js
Labels: 완료, 기능

#20 Rolling post UI 및 To focus 오류 메세지
  src/App.jsx
  src/assets/brandLogo.svg
  src/assets/colorBlue.png
  src/assets/colorGreen.png
  src/assets/colorPink.png
  src/assets/colorToggle.svg
  src/assets/colorYellow.png
  src/assets/imgToggle.svg
  src/assets/switchImgToggle.svg
  src/assets/switchcolorToggle.svg
  src/components/Container.jsx
  src/components/ToggleButton.jsx
  src/main.jsx
  src/pages/UserFormPage.jsx
  src/styles/GlobalStyles.jsx
Labels: 완료

#36 api 함수 보강 / test 완료
  src/App.test.jsx
  src/api/etcApi.js
  src/api/messageApi.js
  src/api/recipientApi.js
Labels: 완료, 기능

#35 메인 페이지 토글 버튼 및 버튼 활성화에 따른 이미지 렌더링 구현
  src/assets/background-img1.jpg
  src/assets/background-img2.jpg
  src/assets/background-img3.jpg
  src/assets/background-img4.jpg
  src/assets/checkIcon.svg
  src/components/Button/ToggleButton.jsx
  src/components/Container.jsx
  yarn.lock
Labels: 완료, 기능

#42 /post/:id/message 페이지 기능 구현
  index.html
  package.json
  src/App.jsx
  src/api/messageApi.js
  src/assets/arrow-top.svg
  src/components/Button/Button.jsx
  src/components/Container.jsx
  src/components/InputBox.jsx
  src/components/ListSlider.jsx
  src/components/ProfileImage.jsx
  src/components/QuillEditor.jsx
  src/components/SectionTitle.jsx
  src/components/SelectBox.jsx
  src/pages/PostId.jsx
  src/pages/PostIdMessage.jsx
  src/styles/reset.jsx
  yarn.lock
Labels: 완료, 기능

#40 #9 feat : input값 비활성화시 생성 버튼 비활성화, 값 활성화 시 버튼 활성화
  package.json
  src/api/recipientApi.js
  src/components/Button/ToggleButton.jsx
  src/components/Container.jsx
  src/components/Header.jsx
  yarn.lock
Labels: 버그, 질문, 기능

#45 사용자에게 값을 전달받아 post하는 기능 구현
  package.json
  src/assets/beige.png
  src/assets/blue.png
  src/assets/green.png
  src/assets/purple.png
  src/components/Button/ToggleButton.jsx
  src/components/Container.jsx
Labels: 완료, 기능

#48 POST 페이지 최종 완성
  package.json
  src/components/Button/ToggleButton.jsx
  src/components/Container.jsx
  src/pages/Post.jsx
  yarn.lock
Labels: 완료, 기능

#54 Message 페이지 보충
  src/components/Button/Button.jsx
  src/pages/PostIdMessage.jsx
Labels: 완료, 기능
